services:
  api:
    build:
      context: src/api
      dockerfile: Dockerfile
    develop:
      watch:
        - path: src/config
          action: rebuild          
    ports:
      - "5100:8080"
    environment:
      - PYTHON_ENV=development
      - DEBUG=1
      - PORT=8080
      - CONFIG_PATH=/app/settings.json
      - BOOKS_DATA_PATH=/app/data/books_data.csv
      - BOOKS_RATING_PATH=/app/data/books_rating.csv
    volumes:
      - ./src/cfg/settings.json:/app/settings.json:ro
      - ./src/api/data:/app/data:ro
