{{- if .Values.provider.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.ingress.tls.secretName | default "app-config-tls" }}
  namespace: azappconfig-system
  labels:
    app.kubernetes.io/component: certificate-trust
data:
  tls.crt: |
{{ .Values.certificates.data.crt | b64dec | nindent 4 }}
{{- end }}