{{- if .Values.provider.enabled }}
apiVersion: azconfig.io/v1
kind: AzureAppConfigurationProvider
metadata:
  name: app-config-provider
spec:
  connectionStringReference: app-config-connection
  target:
    configMapName: {{ .Values.configMap.name }}
    configMapData:
      key: {{ .Values.configMap.data.key | quote }}
      type: {{ .Values.configMap.data.type | default "json" | quote }}
      separator: {{ .Values.configMap.data.separator | default "__" | quote }}
  configuration:
    selectors:
{{- range .Values.provider.selectors }}
      - keyFilter: {{ .keyFilter | default "*" | quote }}
{{- if .labelFilter }}
        labelFilter: {{ .labelFilter | quote }}
{{- end }}
{{- end }}
    refresh:
      enabled: true
      interval: {{ .Values.provider.refreshInterval | default "30s" | quote }}
  featureFlag:
    selectors:
{{- range .Values.provider.selectors }}
      - keyFilter: {{ .keyFilter | default "*" | quote }}
{{- if .labelFilter }}
        labelFilter: {{ .labelFilter | quote }}
{{- end }}
{{- end }}
    refresh:
      enabled: true
      interval: {{ .Values.provider.refreshInterval | default "30s" | quote }}
{{- end }}