apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.host | default "app" }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: {{ .Chart.Name }}-app
