apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-api
  annotations:
    reloader.stakater.com/auto: "true"
    reloader.stakater.com/rollout-strategy: "restart"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Chart.Name }}-api
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}-api
    spec:
      containers:
        - name: {{ .Chart.Name }}-api
          image: "{{ .Values.api.image.repository }}:{{ .Values.api.image.tag }}"
          ports:
            - containerPort: 8080
          env:
            - name: PYTHON_ENV
              value: "development"
            - name: DEBUG
              value: "1"
            - name: PORT
              value: "8080"
            - name: CONFIG_PATH
              value: "/app/settings.json"
            - name: BOOKS_DATA_PATH
              value: "/app/data/books_data.csv"
            - name: BOOKS_RATING_PATH
              value: "/app/data/books_rating.csv"
            - name: CORS_ORIGINS
              value: "https://{{ .Values.app.host }}.{{ .Values.ingress.domain }}"
          volumeMounts:
            - name: config-volume
              mountPath: /app/settings.json
              subPath: settings.json
              readOnly: true
          resources:
            requests:
              memory: "{{ .Values.api.resources.requests.memory }}"
              cpu: "{{ .Values.api.resources.requests.cpu }}"
            limits:
              memory: "{{ .Values.api.resources.limits.memory }}"
              cpu: "{{ .Values.api.resources.limits.cpu }}"
      volumes:
      - name: config-volume
        configMap:
          name: {{ .Values.configMap.name }}
