apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-api
  annotations:
    reloader.stakater.com/auto: "true"
    reloader.stakater.com/rollout-strategy: "restart"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Chart.Name }}-api
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}-api
    spec:
      containers:
        - name: {{ .Chart.Name }}-api
          image: "{{ .Values.api.image.repository }}:{{ .Values.api.image.tag }}"
          ports:
            - containerPort: {{ .Values.api.port | default 8080 }}
          env:
{{- range .Values.api.env }}
            - name: {{ .name }}
              value: {{ .value | quote }}
{{- end }}
            - name: CONFIG_PATH
              value: {{ .Values.api.configPath | default "/app/settings.json" | quote }}
            - name: CORS_ORIGINS
              value: "https://{{ .Values.app.host }}.{{ .Values.ingress.domain }}"
          volumeMounts:
            - name: config-volume
              mountPath: {{ .Values.api.configPath | default "/app/settings.json" }}
              subPath: {{ .Values.configMap.data.key | default "settings.json" }}
              readOnly: true
            - name: data-volume
              mountPath: {{ .Values.volume.mountPath | default "/app/data" }}
              readOnly: true
          resources:
            requests:
              memory: "{{ .Values.api.resources.requests.memory }}"
              cpu: "{{ .Values.api.resources.requests.cpu }}"
            limits:
              memory: "{{ .Values.api.resources.limits.memory }}"
              cpu: "{{ .Values.api.resources.limits.cpu }}"
      volumes:
      - name: config-volume
        configMap:
          name: {{ .Values.configMap.name }}
      - name: data-volume
        hostPath:
          path: {{ .Values.volume.hostPath.path | default "/mnt/data" }}
          type: {{ .Values.volume.hostPath.type | default "DirectoryOrCreate" }}
