apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.api.host | default "api" }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: {{ .Chart.Name }}-api
